use bigdecimal::BigDecimal;
use std::str::FromStr;
use uuid::Uuid;

use crate::api::dto::booking::{BookingDTO, CreateBookingDTO};
use crate::domain::models::booking::{Booking, CreateBooking};

impl From<Booking> for BookingDTO {
    fn from(value: Booking) -> Self {
        Self {
            id: value.id,
            display_code: value.display_code,
            user_id: value.user_id,
            booking_type: value.booking_type,
            status: value.status,
            membership_tier_snapshot: value.membership_tier_snapshot,
            estimated_cost: value.estimated_cost.to_string().parse().unwrap_or(0.0),
            final_cost: value.final_cost.to_string().parse().unwrap_or(0.0),
            payment_status: value.payment_status,
            special_requests: value.special_requests,
            admin_notes: value.admin_notes,
            assigned_employee_id: value.assigned_employee_id,
            details: value.details,
            created_at: value.created_at,
            updated_at: value.updated_at,
        }
    }
}

impl CreateBookingDTO {
    pub fn into_entity(self, user_id: Uuid) -> CreateBooking {
        CreateBooking {
            display_code: String::new(), // generated by BookingServiceImpl::create
            user_id,
            booking_type: self.booking_type,
            membership_tier_snapshot: self.membership_tier_snapshot,
            estimated_cost: BigDecimal::from_str(&self.estimated_cost.to_string())
                .unwrap_or_default(),
            special_requests: self.special_requests,
            details: self.details,
        }
    }
}
